name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/v1/services/<your-service-uuid>/deployments \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}' \
        -H 'Content-Type: application/json' \
        -d '{
          "branch": "main"
        }'
